name: Release

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow only when a tag starting with "v" is pushed

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu

    - name: Build project
      run: cargo build --release --target=x86_64-unknown-linux-gnu

    - name: Create release directory
      run: mkdir -p release

    - name: Copy binary to release directory
      run: cp target/x86_64-unknown-linux-gnu/release/doni ./release/

    - name: Upload release asset
      uses: actions/upload-artifact@v3
      with:
        name: doni-x86_64-linux
        path: ./release/doni

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/doni
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
